import type { Metadata } from "next";
import "./globals.css";
import ApolloSetting from "@/commons/settings/apollo-setting";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props) {
  return (
    <html lang="en">
      <body className="antialiased">
        <ApolloSetting>{props.children}</ApolloSetting>
      </body>
    </html>
  );
}
