// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout(props) {
  return (
    <html lang="en">
      <body>
        <div>==========여기위는 레이아웃입니다 ========== </div>
        {props.children}
        <div>==========여기아래는 레이아웃입니다 ========== </div>
      </body>
    </html>
  );
}

/*
  [ Next 실행 순서 ]

  1. 주소창에 주소 입력
    => http://localhost:3000/

  2. 입력된 주소의 폴더안의 pages.tsx 찾기
    => app/page.tsx
      (ex, 주소: /mypage 라면? app/mypage/page.tsx 찾기)

  3. 해당 페이지컴포넌트를 통째로 props에 넣어서 실행하기
  <RootLayout children={페이지컴포넌트} />

*/
