// import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout(props) {
  return (
    <html lang="en">
      <body>
        <div>===========여기위는 레이아웃입니다===========</div>
        {props.children}
        <div>===========여기아래는 레이아웃입니다===========</div>
      </body>
    </html>
  );
}
